/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages.pb-c.h"
void   profile__init
                     (Profile         *message)
{
  static Profile init_value = PROFILE__INIT;
  *message = init_value;
}
size_t profile__get_packed_size
                     (const Profile *message)
{
  assert(message->base.descriptor == &profile__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t profile__pack
                     (const Profile *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &profile__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t profile__pack_to_buffer
                     (const Profile *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &profile__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Profile *
       profile__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Profile *)
     protobuf_c_message_unpack (&profile__descriptor,
                                allocator, len, data);
}
void   profile__free_unpacked
                     (Profile *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &profile__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   config__init
                     (Config         *message)
{
  static Config init_value = CONFIG__INIT;
  *message = init_value;
}
size_t config__get_packed_size
                     (const Config *message)
{
  assert(message->base.descriptor == &config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t config__pack
                     (const Config *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t config__pack_to_buffer
                     (const Config *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Config *
       config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Config *)
     protobuf_c_message_unpack (&config__descriptor,
                                allocator, len, data);
}
void   config__free_unpacked
                     (Config *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   command__init
                     (Command         *message)
{
  static Command init_value = COMMAND__INIT;
  *message = init_value;
}
size_t command__get_packed_size
                     (const Command *message)
{
  assert(message->base.descriptor == &command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t command__pack
                     (const Command *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t command__pack_to_buffer
                     (const Command *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Command *
       command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Command *)
     protobuf_c_message_unpack (&command__descriptor,
                                allocator, len, data);
}
void   command__free_unpacked
                     (Command *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ack__init
                     (Ack         *message)
{
  static Ack init_value = ACK__INIT;
  *message = init_value;
}
size_t ack__get_packed_size
                     (const Ack *message)
{
  assert(message->base.descriptor == &ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ack__pack
                     (const Ack *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ack__pack_to_buffer
                     (const Ack *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ack *
       ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ack *)
     protobuf_c_message_unpack (&ack__descriptor,
                                allocator, len, data);
}
void   ack__free_unpacked
                     (Ack *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   event__init
                     (Event         *message)
{
  static Event init_value = EVENT__INIT;
  *message = init_value;
}
size_t event__get_packed_size
                     (const Event *message)
{
  assert(message->base.descriptor == &event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t event__pack
                     (const Event *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t event__pack_to_buffer
                     (const Event *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Event *
       event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Event *)
     protobuf_c_message_unpack (&event__descriptor,
                                allocator, len, data);
}
void   event__free_unpacked
                     (Event *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   secret__init
                     (Secret         *message)
{
  static Secret init_value = SECRET__INIT;
  *message = init_value;
}
size_t secret__get_packed_size
                     (const Secret *message)
{
  assert(message->base.descriptor == &secret__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t secret__pack
                     (const Secret *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &secret__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t secret__pack_to_buffer
                     (const Secret *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &secret__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Secret *
       secret__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Secret *)
     protobuf_c_message_unpack (&secret__descriptor,
                                allocator, len, data);
}
void   secret__free_unpacked
                     (Secret *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &secret__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor profile__field_descriptors[2] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Profile, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pwd",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Profile, pwd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned profile__field_indices_by_name[] = {
  1,   /* field[1] = pwd */
  0,   /* field[0] = uid */
};
static const ProtobufCIntRange profile__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor profile__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Profile",
  "Profile",
  "Profile",
  "",
  sizeof(Profile),
  2,
  profile__field_descriptors,
  profile__field_indices_by_name,
  1,  profile__number_ranges,
  (ProtobufCMessageInit) profile__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t config__port__default_value = 1883;
static const ProtobufCFieldDescriptor config__field_descriptors[6] =
{
  {
    "network",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Config, network),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "board",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Config, board),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Config, host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Config, has_port),
    offsetof(Config, port),
    NULL,
    &config__port__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alive_period",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Config, has_alive_period),
    offsetof(Config, alive_period),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "secure",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Config, has_secure),
    offsetof(Config, secure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned config__field_indices_by_name[] = {
  4,   /* field[4] = alive_period */
  1,   /* field[1] = board */
  2,   /* field[2] = host */
  0,   /* field[0] = network */
  3,   /* field[3] = port */
  5,   /* field[5] = secure */
};
static const ProtobufCIntRange config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Config",
  "Config",
  "Config",
  "",
  sizeof(Config),
  6,
  config__field_descriptors,
  config__field_indices_by_name,
  1,  config__number_ranges,
  (ProtobufCMessageInit) config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor command__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Command, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Command, has_seq),
    offsetof(Command, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "svals",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Command, n_svals),
    offsetof(Command, svals),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ivals",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Command, n_ivals),
    offsetof(Command, ivals),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned command__field_indices_by_name[] = {
  0,   /* field[0] = id */
  3,   /* field[3] = ivals */
  1,   /* field[1] = seq */
  2,   /* field[2] = svals */
};
static const ProtobufCIntRange command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Command",
  "Command",
  "Command",
  "",
  sizeof(Command),
  4,
  command__field_descriptors,
  command__field_indices_by_name,
  1,  command__number_ranges,
  (ProtobufCMessageInit) command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ack__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ack, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ack, has_seq),
    offsetof(Ack, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Ack, has_status),
    offsetof(Ack, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ack__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = seq */
  2,   /* field[2] = status */
};
static const ProtobufCIntRange ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Ack",
  "Ack",
  "Ack",
  "",
  sizeof(Ack),
  3,
  ack__field_descriptors,
  ack__field_indices_by_name,
  1,  ack__number_ranges,
  (ProtobufCMessageInit) ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor event__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Event, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "svals",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Event, n_svals),
    offsetof(Event, svals),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fvals",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Event, n_fvals),
    offsetof(Event, fvals),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ivals",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(Event, n_ivals),
    offsetof(Event, ivals),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned event__field_indices_by_name[] = {
  2,   /* field[2] = fvals */
  0,   /* field[0] = id */
  3,   /* field[3] = ivals */
  1,   /* field[1] = svals */
};
static const ProtobufCIntRange event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Event",
  "Event",
  "Event",
  "",
  sizeof(Event),
  4,
  event__field_descriptors,
  event__field_indices_by_name,
  1,  event__number_ranges,
  (ProtobufCMessageInit) event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor secret__field_descriptors[1] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Secret, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned secret__field_indices_by_name[] = {
  0,   /* field[0] = key */
};
static const ProtobufCIntRange secret__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor secret__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Secret",
  "Secret",
  "Secret",
  "",
  sizeof(Secret),
  1,
  secret__field_descriptors,
  secret__field_indices_by_name,
  1,  secret__number_ranges,
  (ProtobufCMessageInit) secret__init,
  NULL,NULL,NULL    /* reserved[123] */
};
